### ISSUE TITLE
Could not connect to HA

### ISSUE THREAD

**Issue by seffyroff** [gensyn/de_gensyn_HomeAssistantPlugin#11] opened 2024-07-05 20:29 UTC
OS: Manjaro Gnome
StreamController Version: 1.5.0-beta.6 (installed via Flatpak)
HomeAssistantPlugin Version: 0.9.3-beta (installed via StreamController Store UI)

After adding the HA action to a button, and providing the Host, Port and Token, the plugin is unable to connect to my HA instance. 

Log entries:

```
Jul 05 13:14:39 REDXIII com.core447.StreamController.desktop[92264]: 2024-07-05 13:14:39.507 | ERROR    | plugins.de_gensyn_HomeAssistantPlugin.backend.home_assistant:_auth:233 - Could not connect to %s: %s
Jul 05 13:14:49 REDXIII com.core447.StreamController.desktop[92264]: 2024-07-05 13:14:49.509 | ERROR    | plugins.de_gensyn_HomeAssistantPlugin.backend.home_assistant:_auth:233 - Could not connect to %s: %s
Jul 05 13:15:08 REDXIII com.core447.StreamController.desktop[92264]: 2024-07-05 13:15:08.498 | ERROR    | plugins.de_gensyn_HomeAssistantPlugin.backend.home_assistant:_auth:233 - Could not connect to %s: %s
```

My HA instance is not SSL, and is accessible from a web browser on the same host as StreamController at homeassistant.local:8123.  I have also tried connecting via IP address.

Websocket API is enabled in HA configuration.yaml with a single line:
`websocket_api:
`
I do not see any log entries in HA Core or Supervisor related to 'websocket' or similar.

**Comment by seffyroff** [comment] 2024-07-05 20:42
It is working now, closeing issue.

seems like it is working by IP, not hostname.  That's probably a 'me thing'.  I did try IP previously and it failed.  I think what happened was, when I tried to change the host from homeassistant.local to the IP, StreamController locks up as soon as I started editing that field.  Looking in the settings.json for the plugin, it received my first keypress '1' only in "host".  Editing the Json manually to add the IP fixes it.

**Comment by fcrozat** [comment] 2024-08-20 11:28
I would suggest to reopen, there is a bug in the UI which is not waiting until all digits are entered for port field (similar to what you described with host field). It is trying to validate immediately after the first keystroke.

**Comment by gensyn** [comment] 2024-08-20 11:56
Yeah, I'm reacting to each value-changed event. What would you prefer? Try to connect when the field loses focus? Try to connect after no new digit after, say, two seconds?

**Comment by fcrozat** [comment] 2024-08-20 11:58
I'd say when focus is lost. 

In my case, it was stopping on first digit and causing the entire application to freeze (trying to connect to port 4 instead of 443, causing a lot of GUI locked, waiting for timeout).

**Comment by gensyn** [comment] 2024-08-20 12:00
For now that is expected behavior but I never had my application freeze because of it and no one else complained until now. You are right though; it's not very pretty.

**Comment by gensyn** [comment] 2024-11-08 08:14
Since there are no other complaints, I am closing this for now.

**Closed by gensyn** 2024-11-08 08:14 UTC
